language: node_js
node_js:
  - "8.11.3"

services:
  - postgresql

env:
  global:
    - CC_TEST_REPORTER_ID=afe0dc4811f07679b005aa43f0e1fec65fc9d1cda33042a4ab9267d6fd08bb6a
    - TEST_DB_PASS=
    - TEST_DB_HOST=localhost
    - TEST_DB_USER=postgres
    - TEST_DB_DATABASE=wayfarer_test
    - JWT_KEY=secret
    - email=ephraimappdev@gmail.com
    - password=apptesting14@
    - CLOUDINARY_CLOUD_NAME=ephaig
    - CLOUDINARY_API_KEY=666632364858846
    - CLOUDINARY_API_SECRET=gkNXpAjK2BhnDtYaqBY83B3pi0o

before_script:
  - psql -c 'CREATE DATABASE wayfarer_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run test:db:dev

after_script:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
